version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    env_file:
      - ./db/db.env

  web:
    build: ./backend
    command: gunicorn blogpost.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/media_cdn:/app/media_cdn
      - ./backend/static_cdn:/app/static_cdn
      - ./backend/images:/app/images
      - ./backend/static:/app/static

    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
  
volumes:
  postgres_data:
  media_volume:
  statuc_volume:
  images_volume: